[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
berrie_bridge = "EP1N2w7ijCboXHJS6mfysTWu2vQohP933ny2cHovSxfU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/athdoSSvTJoAxt9DY7cFrbGynu7Bv1MQUUB8NSstAD3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
